---
title: "Birds in Romania - 2 Visualization"
author: "Sonia Balan"
date: "2023-09/10"

Data Info:
  Username: soniaa.balan
  Format: SIMPLE_CSV
  Download key: 0018307-230828120925497
  Created: 2023-09-16T09:31:59.821+00:00
  Citation Info:  
    Please always cite the download DOI when using this data.
    https://www.gbif.org/citation-guidelines
    DOI: 10.15468/dl.y8qsxq
    Citation:
    GBIF Occurrence Download https://doi.org/10.15468/dl.y8qsxq Accessed from R via rgbif(https://github.com/ropensci/rgbif) on 2023-09-16

---

```{r}
# install.packages("ggplot2")
# install.packages("dplyr")
# install.packages("sf")
# install.packages("ggmap")
# install.packages("gridExtra")

library(ggplot2)
library(dplyr)
library(sf)
library(gridExtra)
library(ggmap)

# load data from file
data_vis <- read.csv("data_clean.csv",
                 header=TRUE,
                 stringsAsFactors=TRUE)
data_vis$eventDate <- as.Date(data_vis$eventDate)

'HOTFIX'
column_index <- which(colnames(data_vis) == "stateProvince.stateProvince")
colnames(data_vis)[column_index] <- "stateProvince"
```

  Accounting for Count Data
```{r}
# function to obtain the accurate number of counts per feature
process_counts_per_feature <- function(df, feature, taxon_level) {
  counts <- df %>%
  group_by(.data[[feature]], .data[[taxon_level]]) %>%
  summarise(total_count = sum(individualCount))
  
  return(counts)
}

# getting he total number of occuernces per taxon level (to be used for normalization)
process_counts <- function(df, taxon_level){
  counts <- df %>%
  group_by(.data[[taxon_level]]) %>%
  summarise(total_count = sum(individualCount))
  
  return(counts)
}
 
```
# Diagnostics Plots -------------------------------
  Cutoff Decision
```{r}
# aes(x = Start.date %>% format('%Y'))
threshold = 2013 #threshold year
ggplot(data_vis,aes(eventDate %>% format('%Y'))) +
  geom_bar(fill = "#00501B") +
  geom_vline(xintercept = threshold,
             linewidth = 0.5,
             color = "black")
```
# per time
```{r}
# ---------------
data_vis <-data_vis %>%
  filter(eventDate >= as.Date("2013-01-01"))

# Occurences per time unit ------
# nr of occurences/year
ggplot(data_vis, aes(eventDate %>% format('%Y'))) +
  geom_bar(fill = "#0E6251")+
  labs(title = paste("Occurences per Year"),
     x = "Year",
     y = "Count")

# nr of occurences/month 
data_vis %>%
  group_by(month = eventDate %>% format('%b')) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = month, y = count, fill = count)) +
  geom_bar(stat = "identity") +
  labs(title = paste("Occurences per Month"),
     x = "Month",
     y = "Count") +
  # scale_fill_continuous(low = "darkslategray3", high = "maroon") + 
  scale_x_discrete(limits = c("Jan", "Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))

# nr of occurences/day
ggplot(data_vis, aes(eventDate %>% format('%d'))) +
  geom_bar(fill = "#1B4F72") +
  labs(title = paste("Occurences per Day"),
     x = "Day",
     y = "Count")

# nr of occurences/weekday
ggplot(data_vis, aes(eventDate %>% format('%a'))) +
  geom_bar(fill = "#1B4F72") +
  labs(title = paste("Occurences per Weekday"),
     x = "Weekday",
     y = "Count") +
  scale_x_discrete(limits = c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"))
```

# occurences per location
```{r}
# province
prov <- data_vis %>%
  group_by(stateProvince) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  top_n(11,n)
prov <- prov[-1,] # the top entry is NA

# color_scale <- scale_fill_gradient(low = "lightblue", high = "darkblue")
ggplot(prov, aes(x = reorder(stateProvince,n), y = n, fill = n)) +
  geom_bar(stat = "identity") +
  # coord_polar("y", start=0) + 
  scale_fill_continuous(low="lightgreen", high="darkblue") +
  labs(title = paste("Occurences per County"),
     x = "County",
     y = "Count")

# latitude and longitude
latitude_barplot <- ggplot(data_vis, aes(decimalLatitude)) +
  geom_histogram(fill = "#1B4F72") +
  labs(title = paste("Occurences per Latitude"),
     x = "Latitude",
     y = "Count")
longitude_barplot <- ggplot(data_vis, aes(decimalLongitude)) +
  geom_histogram(fill = "#1B4F72") +
  labs(title = paste("Occurences per Longitude"),
     x = "Longitude",
     y = "Count")
grid.arrange(latitude_barplot, longitude_barplot, nrow = 2)
```

# Map View
```{r}
cities_list <- read.csv("orase.csv", stringsAsFactors = T)
cities_list = cities_list %>% select(c("X",
                                       "Y",
                                       "NUME",
                                       "JUDET",
                                       "POPULATIE..in.2002."))


# rename columns
colnames(cities_list) = c("decimalLongitude","decimalLatitude","locality","stateProvince","population")
# find the capital of each province
centers <-cities_list %>%
  group_by(stateProvince) %>%
  slice_max(population, n = 1) %>%
  ungroup() %>%
  filter(!grepl("Sectorul", locality)| is.na(locality))

top_centers <- centers[centers$stateProvince %in% prov$stateProvince, ]

ggplot(data_vis,
       aes(x = decimalLongitude,
           y = decimalLatitude)) + 
  geom_point(alpha = 0.01, 
             size = 0.25) +
  # coord_equal() +
  xlab('Longitude') + 
  ylab('Latitude') + 
  stat_density2d(aes(fill = ..level..), alpha = .75,
                 geom = "polygon", data = data_vis) +
  scale_fill_viridis_c() +
  # theme(legend.position = 'none') 
  xlim(20,30) +
  ylim(min(data_vis$decimalLatitude),max(data_vis$decimalLatitude)) +
  geom_text(data = top_centers, 
            aes(x = decimalLongitude, y = decimalLatitude, label = stateProvince),
            size = 3, color = "black") + 
  geom_label(data = top_centers, 
             aes(x = decimalLongitude, y = decimalLatitude, label = stateProvince),
             size = 3, fill = "white", alpha = 0.4)  
```


# Changes over time
```{r}
# top species ------
spp_total <- process_counts(data_vis, "species")
spp_top <- head(spp_total[order(spp_total$total_count, decreasing = TRUE), ], 11)
spp_top_sans1 <- spp_top[-1,]

# most abundent birds (overall)
ggplot(spp_top,
       aes(x = reorder(species, total_count),
           y = total_count,
           fill = total_count)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  scale_fill_continuous(low="lightgreen", high="darkblue") +
  labs(title = paste("Top Species"),
     x = "Species",
     y = "Abundance")

# most abundent birds (overall), without Anser albiformis (outlier?)
ggplot(spp_top_sans1,
       aes(x = reorder(species, total_count),
           y = total_count,
           fill = total_count)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  scale_fill_continuous(low="lightgreen", high="darkblue") +
  labs(title = paste("Top Species"),
     x = "Species",
     y = "Abundance")

# top genus --------
gen_total <- process_counts(data_vis, "genus")
gen_top <- head(gen_total[order(gen_total$total_count, decreasing = TRUE), ], 12)
# most abundent birds (overall)
ggplot(gen_top, aes(x = reorder(genus, total_count), y = total_count, fill = total_count)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  labs(title = paste("Top Genuses"),
     x = "Genus",
     y = "Abundance")
# most abundent birds (overall) without waxwings
gen_top_sans1 <- gen_top[-1,]
ggplot(gen_top_sans1, aes(x = reorder(genus, total_count), y = total_count, fill = total_count)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  labs(title = paste("Top Genuses"),
     x = "Genus",
     y = "Abundance")
```

# 
```{r}
# plot all months ----
ord_per_month <- process_counts_per_feature(data_vis %>% mutate(formatted_date = format(eventDate, "%b")), "formatted_date", "order")

ggplot(ord_per_month,
       aes(x = formatted_date,
           y = order, 
           fill = total_count)) +
  geom_line() +
  geom_point() +
  theme(legend.position="none") +
  labs(title = "Presence/month by Order",
       x = "Month")
#  + color seasons in the background
# 
# species per month
fam_per_month <- process_counts_per_feature(data_vis, eventDate %>% format('%b'), "family")
# spp_per_month_norm # ???

ggplot(fan_per_month, aes(month , y = total_count, color = order)) +
  geom_line() +
  # geom_point() +
  # theme(legend.position="none") +
  labs(title = "Presence/month by Family",
       x = "Month")

```


