---
title: "Birds in Romania"
output: html_document
date: "2023-09-14"

Data Info:
  Username: soniaa.balan
  Format: SIMPLE_CSV
  Download key: 0018307-230828120925497
  Created: 2023-09-16T09:31:59.821+00:00
  Citation Info:  
    Please always cite the download DOI when using this data.
    https://www.gbif.org/citation-guidelines
    DOI: 10.15468/dl.y8qsxq
    Citation:
    GBIF Occurrence Download https://doi.org/10.15468/dl.y8qsxq Accessed from R via rgbif(https://github.com/ropensci/rgbif) on 2023-09-16

---

# Setup 
```{r} 
# Libraries install
# install.packages("rstudioapi")
# install.packages("rgbif")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("stringr")
# install.packages("stringdist")

# Libraries loading
library(rgbif)
library(dplyr)
library(ggplot2)
library(stringr)
library(rstudioapi)
library(stringdist)

# set wrok environment
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
```

# Retrieve Data from GBIF using their API
```{r}
# # download occurrence data
# occ_download(
#   # filters applied
#   pred("taxonKey", 212), # aves - all bird species
#   pred("country","RO"), # Romania
#   format = "SIMPLE_CSV",
#   # accreditation
#   user = "soniaa.balan",
#   pwd = "not_a_real_password", # for safety reasons, the password is not included in this script
#   email = "soniaa.balan@gmail.com"
# )

# # check download status - also returns Download information
# occ_download_wait('0018307-230828120925497')

# retrieve downloaded data
data_raw<- occ_download_get('0018307-230828120925497') %>%
  occ_download_import()

# remove irrelevant and uninformative (no available data) columns
remove_vars = c("datasetKey",
                "occurrenceID",
                "kingdom",
                "phylum",
                "class",
                "verbatimScientificNameAuthorship",
                "countryCode",
                "publishingOrgKey",
                "coordinatePrecision",
                "elevation",
                "elevationAccuracy",
                "depth",
                "depthAccuracy",
                "taxonKey",
                "speciesKey",
                "catalogNumber",
                "recordNumber",
                "license",
                "rightsHolder",
                "establishmentMeans",
                "lastInterpreted",
                "recordedBy",
                "typeStatus",
                "mediaType",
                "issue",
                "institutionCode",
                "identifiedBy",
                "publishingOrgKey",
                "datasetKey",
                "occurrenceID",
                "taxonRank",
                "scientificName")

data = data_raw %>% select(-remove_vars)
```


# Data Cleaning ----------------------------------------------------------------
  General Cleaning
```{r}
# remove samples with no informative taxonomic data
data <- data[-which(data$order == ""), ]
data <- data[!is.na(data$order), ]

# factorize data stored as characters
data[sapply(data, is.character)] <- lapply(data[sapply(data, is.character)],as.factor)
data$month <- as.factor(data$month)

# replace NAs in count data by 1
data$individualCount <- replace(data$individualCount, is.na(data$individualCount), 1)
data$individualCount <- replace(data$individualCount, data$individualCount == 0, 1)

# summaries of remaining columns - for debugging
for (var in colnames(data)) {
  print(summary(data[,var]))
}
```
  Taxonomy Labels
```{r}

##### Renaming verbatim scientific name levels #####
lvl_verbatim = levels(data$verbatimScientificName)
verbatim_sp <- lapply(lvl_verbatim, function(x) word(x, 1, 2))
levels(data$verbatimScientificName) = unlist(verbatim_sp)

# add species information from verbatimScientificName 
data$species <- as.character(data$species)
data[which(data$species==""),"species"] <-   as.vector(data[(data$species==""),"verbatimScientificName"])
data$species <- as.factor(data$species)

# add genus information from species
gen <- lapply(data[data$genus=="" & !is.na(data$species),"species"], function(x) word(x, 1))

data$genus <- as.character(data$genus)
data[which(data$genus=="" & !is.na(data$species)),"genus"] <- as.vector(gen)
data[data$genus=="","genus"] <- NA
data$genus <- as.factor(data$genus)

# sanity checks
print(which(data$species=="")) # there shouldn't be any more empty species
print(which(data$genus=="")) # there shouldn't be any more empty genus

data = data %>% select(-c("verbatimScientificName"))
```
  Dates
```{r}
print("before")
print(sum(is.na(data$year)))
print(sum(is.na(data$month)))
print(sum(is.na(data$day)))

# add missing year information from other columns 
data$year[which(is.na(data$year) & !is.na(data$dateIdentified))] <- as.numeric(
  format(
    data$dateIdentified[which(
      is.na(data$year) & !is.na(data$dateIdentified))],
    '%Y'))

# add missing day information from other columns
data$day[which(is.na(data$day) & !is.na(data$dateIdentified))] <- as.numeric(
  format(
    data$dateIdentified[which(
      is.na(data$day) & !is.na(data$dateIdentified))],
    '%d'))

# add missing month information from other columns
data$month[which(is.na(data$month) & !is.na(data$dateIdentified))] <- as.factor(
  format(
    data$dateIdentified[which(
      is.na(data$month) & !is.na(data$dateIdentified))],
    '%m'))

data$eventDate <- replace(data$eventDate, is.na(data$eventDate), data$dateIdentified)

# remaining NAs
print("after")
print(sum(is.na(data$year)))
print(sum(is.na(data$month)))
print(sum(is.na(data$day)))
# note - forgot to run from begining and after adding the data from dateIdentified, eventDate doesn't add anyting new.

# data = data %>% select(-c("dateIdentified"))
```
  Location Data
  city/county database from https://github.com/romania/localitati
```{r}
cities_list <- read.csv("orase.csv")
cities_list = cities_list %>% select(-c("JUDET.AUTO",
                                        "POPULATIE..in.2002.",
                                        "REGIUNE"))
# rename columns
colnames(cities_list) = c("decimalLongitude","decimalLatitude","locality","stateProvince")

test = data[,c("locality", "stateProvince","decimalLatitude","decimalLongitude")]
print(sum(test$stateProvince==""))

missing_indices <- which(test$stateProvince=="" & test$locality!="")
state_provences <- character(length(missing_indices))

# time-consuming step - can still parallelize
for (i in missing_indices) {
  
  distances <- stringdist(test$locality[i], cities_list$locality)
  closest_index <- which.min(distances)
  if (distances[closest_index] < 0.5) {
    state_provences[i] <- cities_list$stateProvince[closest_index]
  } else {
    state_provences[i] <- NA 
  }
}

test$stateProvince[missing_indices] <- as.factor(state_provences)

print(sum(is.na(test$stateProvince)))
```
  Accounting for Count Data
```{r}
# function to obtain the accurate number of counts per feature
process_counts_per_feature <- function(df, feature, taxon_level) {
  counts <- df %>%
  group_by(.data[[feature]], .data[[taxon_level]]) %>%
  summarise(total_count = sum(individualCount))
  
  return(counts)
}

# getting he total number of occuernces per taxon level (to be used for normalization)
process_counts <- function(df, taxon_level){
  counts <- df %>%
  group_by(.data[[taxon_level]]) %>%
  summarise(total_count = sum(individualCount))
  
  return(counts)
}
 
```
# Diagnostics Plots -------------------------------
  Cutoff Decision
```{r}
ggplot(data,aes(year)) +
  geom_bar(color = "#00501B") +
  geom_vline(xintercept = 2005,
             linewidth = 0.5,
             color = "black") 
```
  More exploratory figures
```{r}
# ---------------
data_vis <- data[which(data$year > 2004 ), ]

# Occurences per time unit ------
# nr of occurences/year
ggplot(data_vis, aes(year)) +
  geom_bar(fill = "#0E6251",
           fill = 0.75)+
  labs(title = paste("Occurences per Year"),
     x = "Month",
     y = "Count")

# nr of occurences/month 
ggplot(data_vis, aes(month, fill = month)) +
  geom_bar(fill = "#1B4F72", 
           alpha = 0.75) +
  labs(title = paste("Occurences per Month"),
     x = "Month",
     y = "Count")

# nr of occurences/day
ggplot(data_vis, aes(day)) +
  geom_bar(fill = "#1B4F72", 
           alpha = 0.75) +
  labs(title = paste("Occurences per Day"),
     x = "Month",
     y = "Count")

# occurences per location ------
# Locality\
loc <- data_vis %>%
  group_by(locality) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  top_n(11,n)
loc <- loc[-which(loc$locality == ""), ]

ggplot(loc, aes(x = reorder(locality, n), y = n, fill = locality)) +
  geom_bar(stat = "identity",
           fill = "#1B4F72", 
           alpha = 0.75) +
    coord_polar("y", start=0) +
  labs(title = paste("Occurences per Locality"),
     x = "Locality",
     y = "Count")

# province
prov <- data_vis %>%
  group_by(stateProvince) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  top_n(11,n)
prov <- prov[-which(prov$stateProvince == ""), ]
  
ggplot(prov, aes(x = reorder(stateProvince,n), y = n, fill = stateProvence)) +
  geom_bar(stat = "identity",
           alpha = 0.75) +
  coord_polar("y", start=0) +
  labs(title = paste("Occurences per County"),
     x = "County",
     y = "Count")

# latitude and longitude
ggplot(data_vis, aes(decimalLatitude)) +
  geom_histogram(fill = "#1B4F72", 
           alpha = 0.75) +
  labs(title = paste("Occurences per Latitude"),
     x = "Latitude",
     y = "Count")
ggplot(data_vis, aes(decimalLongitude)) +
  geom_histogram(fill = "#1B4F72", 
           alpha = 0.75) +
  labs(title = paste("Occurences per Longitude"),
     x = "Longitude",
     y = "Count")

# OBSERVATION BASIS ----------------
ggplot(data_vis, aes(collectionCode)) +
  geom_bar(fill = "#1B4F72", 
           alpha = 0.75) +
  labs(title = paste("Organization"),
     x = "Type",
     y = "Count")



```

# Changes over time
```{r}
# top species ------
spp_total <- process_counts(data_vis, "species")
spp_top <- head(spp_total[order(spp_total$total_count, decreasing = TRUE), ], 11)
spp_top_sans1 <- spp_top[-1,]

# most abundent birds (overall)
ggplot(spp_top, aes(x = reorder(species, total_count), y = total_count, fill = species)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  labs(title = paste("Top Species"),
     x = "Species",
     y = "Abundance")
# most abundent birds (overall), without Anser albiformis (outlier?)
ggplot(spp_top_sans1, aes(x = reorder(species, total_count), y = total_count, fill = species)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  labs(title = paste("Top Species"),
     x = "Species",
     y = "Abundance")

# top genus --------
gen_total <- process_counts(data_vis, "genus")
gen_top <- head(gen_total[order(gen_total$total_count, decreasing = TRUE), ], 12)
# most abundent birds (overall)
ggplot(gen_top, aes(x = reorder(genus, total_count), y = total_count, fill = genus)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  labs(title = paste("Top Genuses"),
     x = "Genus",
     y = "Abundance")
# most abundent birds (overall) without waxwings
gen_top_sans1 <- gen_top[-2,]
ggplot(gen_top_sans1, aes(x = reorder(genus, total_count), y = total_count, fill = genus)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start=0) +
  labs(title = paste("Top Genuses"),
     x = "Genus",
     y = "Abundance")

# plot all months ----
ord_per_month <- process_counts_per_feature(data_vis,"month","order")
ggplot(ord_per_month, aes(month , y = order)) +
  geom_line() +
  geom_point() +
  theme(legend.position="none") +
  labs(title = "Presence/month by Order",
       x = "Month")
#  + color seasons in the background

# species per month
fan_per_month <- process_counts_per_feature(data_vis, "month", "order")
# spp_per_month_norm # ???

ggplot(fan_per_month, aes(month , y = total_count, color = order)) +
  geom_line() +
  # geom_point() +
  # theme(legend.position="none") +
  labs(title = "Presence/month by Family",
       x = "Month")

```
